# Generated by Django 2.1.1 on 2019-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1500)),
                ('alt_name1', models.CharField(max_length=1500)),
                ('alt_name2', models.CharField(max_length=1500)),
                ('alt_name3', models.CharField(max_length=1500)),
                ('alt_name4', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=4000)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='offered_job_profile',
            field=models.ManyToManyField(to='hrdata.Job_Profiles'),
        ),
    ]
