# Generated by Django 2.1.1 on 2019-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alt_name1',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='company',
            name='alt_name2',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='company',
            name='alt_name3',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='company',
            name='alt_name4',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
