# Generated by Django 2.1.1 on 2019-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdata', '0002_auto_20190518_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
                ('email', models.CharField(max_length=1500)),
                ('alt_email', models.CharField(blank=True, max_length=1500)),
                ('phone_number', models.CharField(max_length=1500)),
                ('alt_phone_number', models.CharField(blank=True, max_length=1500)),
                ('designation', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
