# Generated by Django 2.1.1 on 2019-05-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrdata', '0003_auto_20190518_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HRDetails',
        ),
    ]
